refactor: git pre-commit hook into multiple files, add prettier

diff --git a/src/utils/gitHooks/pre-commit b/src/utils/gitHooks/pre-commit
--- a/src/utils/gitHooks/pre-commit
+++ b/src/utils/gitHooks/pre-commit
@@ -1,12 +1,27 @@
 #!/bin/sh
-#
-# Pre-commit hook called by "git commit" with no arguments.
-# Checks staged .js(x) files for eslint errors.
-# Exits with non-zero status after issuing an appropriate message if
-# it wants to stop the commit.
-# To activate, place this script in {projectRoot}/.git/hooks/pre-commit
-# or better yet keep it checked in version control by leaving it here and
-# changing git's hook directory to point here:
-# git config core.hooksPath src/utils/gitHooks
 
-git diff --diff-filter=d --cached --name-only | grep "\.js.\?$" | xargs ./node_modules/.bin/eslint
+# Pre-commit hook triggered by every `git commit`.
+# To activate, change git's hook directory and make scripts executable:
+# git config core.hooksPath src/utils/gitHooks
+# chmod -R u+x src/utils/gitHooks
+
+# This hook looks for scripts in ./pre-commit.d directory and executes them in order,
+# passing along stdin. If any script exits with a non-zero status, this script exits.
+# Adapted from https://gist.github.com/mjackson/7e602a7aa357cfe37dadcc016710931b.
+
+hook_dir="$0.d"
+
+if [[ -d $hook_dir ]]; then
+  stdin=$(cat /dev/stdin)
+
+  for hook in $hook_dir/*; do
+    echo "Running $hook hook"
+    echo "$stdin" | $hook "$@"
+
+    exit_code=$?
+
+    if [ $exit_code != 0 ]; then
+      exit $exit_code
+    fi
+  done
+fi
